"""
Base Action for the Execution Engine.

Every execution action must inherit from BaseAction and implement
the execute() method.

The Execution Engine relies on this contract to execute actions
without knowing their internal implementation.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

from app.execution.models import ActionResult, ExecutionAction


class BaseAction(ABC):
    """
    Abstract base class for all execution actions.
    """

    def __init__(self, **dependencies):
        """
        Store shared dependencies (repositories, services, etc.)
        that concrete actions may need.
        """
        self.dependencies = dependencies

    @abstractmethod
    async def execute(
        self,
        action: ExecutionAction,
    ) -> ActionResult:
        """
        Execute a single action.

        Args:
            action: The action generated by the Planning Agent.

        Returns:
            ActionResult describing the outcome.
        """
        raise NotImplementedError