"""
CREATE_TASK execution action.

Converts a Planning Agent CREATE_TASK action into a TaskCreate schema,
delegates persistence to TaskService, and returns a structured ActionResult.
"""

from __future__ import annotations

import logging
from typing import Any

from pydantic import ValidationError

from app.execution.actions.base import BaseAction
from app.execution.models import ActionResult, ActionType, ExecutionAction
from app.schemas.task import TaskCreate
from app.services.task_service import TaskService

logger = logging.getLogger(__name__)


class CreateTaskAction(BaseAction):
    """
    Handler for ActionType.CREATE_TASK.

    Expects a TaskService instance in dependencies under the key
    ``task_service``.
    """

    _DEPENDENCY_KEY = "task_service"

    async def execute(self, action: ExecutionAction) -> ActionResult:
        """
        Execute a CREATE_TASK action.

        Args:
            action: Execution action generated by the Planning Agent.
                The action type must be CREATE_TASK and the payload must
                contain the fields required by TaskCreate.

        Returns:
            ActionResult describing success or failure. Validation and
            dependency errors are returned as failed results rather than
            raised as exceptions.
        """
        logger.debug(
            "[DEBUG task-creation] CreateTaskAction.execute start payload=%s",
            action.payload,
        )

        if action.type != ActionType.CREATE_TASK:
            return self._failure(
                action_type=action.type,
                error=f"Expected action type '{ActionType.CREATE_TASK.value}', "
                f"received '{action.type.value}'.",
            )

        task_service = self._get_task_service()
        if task_service is None:
            return self._failure(
                error="Missing or invalid 'task_service' dependency.",
            )

        try:
            task_create = TaskCreate.model_validate(action.payload)
        except ValidationError as exc:
            return self._failure(
                error="Invalid CREATE_TASK payload.",
                metadata={"validation_errors": exc.errors()},
            )

        logger.debug(
            "[DEBUG task-creation] TaskCreate.model_validate result=%s",
            task_create.model_dump(mode="json"),
        )

        try:
            logger.debug(
                "[DEBUG task-creation] before TaskService.create_task task=%s",
                task_create.model_dump(mode="json"),
            )
            created_task = task_service.create_task(task_create)
        except RuntimeError as exc:
            logger.error(
                "[DEBUG task-creation] CreateTaskAction caught RuntimeError: %s",
                exc,
            )
            return self._failure(
                error=str(exc),
            )

        return ActionResult(
            success=True,
            action_type=ActionType.CREATE_TASK,
            resource_type="task",
            resource_id=created_task.id,
            message="Task created successfully",
        )

    def _get_task_service(self) -> TaskService | None:
        """
        Resolve TaskService from injected dependencies.

        Returns:
            TaskService instance when present and correctly typed,
            otherwise None.
        """
        service = self.dependencies.get(self._DEPENDENCY_KEY)
        if not isinstance(service, TaskService):
            return None
        return service

    def _failure(
        self,
        error: str,
        action_type: ActionType = ActionType.CREATE_TASK,
        metadata: dict[str, Any] | None = None,
    ) -> ActionResult:
        """
        Build a failed ActionResult for CREATE_TASK.

        Args:
            error: Human-readable failure description.
            action_type: Action type to record on the result.
            metadata: Optional structured details about the failure.

        Returns:
            A failed ActionResult.
        """
        return ActionResult(
            success=False,
            action_type=action_type,
            error=error,
            metadata=metadata or {},
        )
