"""
Execution Engine.

Consumes an ExecutionPlan generated by the Planning Agent and
executes each action deterministically.

Responsibilities:
- Validate actions
- Resolve handlers
- Execute actions
- Continue execution even if one action fails
- Collect execution results
"""

from __future__ import annotations

from app.execution.models import (
    ActionResult,
    ExecutionPlan,
)
from app.execution.registry import ActionRegistry


class ExecutionEngine:
    """
    Executes AI-generated execution plans.
    """

    def __init__(
        self,
        registry: ActionRegistry,
        **dependencies,
    ) -> None:
        self.registry = registry
        self.dependencies = dependencies

    async def execute(
        self,
        plan: ExecutionPlan,
    ) -> list[ActionResult]:
        """
        Execute every action in an ExecutionPlan.

        Returns:
            List of ActionResults.
        """

        results: list[ActionResult] = []

        for action in plan.actions:

            if not self.registry.supports(action.type):

                results.append(
                    ActionResult(
                        success=False,
                        action_type=action.type,
                        error=f"No handler registered for '{action.type.value}'",
                    )
                )

                continue

            handler_class = self.registry.get(action.type)

            handler = handler_class(**self.dependencies)

            try:
                result = await handler.execute(action)

            except Exception as exc:

                result = ActionResult(
                    success=False,
                    action_type=action.type,
                    error=str(exc),
                )

            results.append(result)

        return results