"""
Shared data models for the Execution Engine.

These models define the contract between AI agents and the
deterministic execution layer.

The Planning Agent produces an ExecutionPlan.
The Execution Engine consumes it.

AI decides.
Software executes.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field


class ActionType(str, Enum):
    """
    Supported execution actions.
    """

    CREATE_TASK = "CREATE_TASK"
    CREATE_EVENT = "CREATE_EVENT"
    CREATE_ROUTINE = "CREATE_ROUTINE"
    CREATE_DOCUMENT = "CREATE_DOCUMENT"
    UPDATE_TASK = "UPDATE_TASK"
    UPDATE_EVENT = "UPDATE_EVENT"
    SEND_NOTIFICATION = "SEND_NOTIFICATION"


class ExecutionAction(BaseModel):
    """
    Represents a single action that should be executed.
    """

    type: ActionType
    payload: dict[str, Any] = Field(default_factory=dict)


class ExecutionPlan(BaseModel):
    """
    Complete execution plan generated by the Planning Agent.
    """

    actions: list[ExecutionAction] = Field(default_factory=list)


class ActionResult(BaseModel):
    """
    Result of executing a single action.
    """

    success: bool

    action_type: ActionType

    resource_id: UUID | None = None

    resource_type: str | None = None

    message: str = ""

    error: str | None = None

    executed_at: datetime = Field(default_factory=datetime.utcnow)

    metadata: dict[str, Any] = Field(default_factory=dict)